### ISSUE TITLE
Cannot run the `heatmaps` pipeline on "test espression matrix"

### ISSUE THREAD

**Issue by Feat-FeAR** [TCP-Lab/transportome_profiler#27]
`kerblam run heatmaps -l --profile test` does not work because:
1. _espression matrix_ is downloaded as a __TSV__ compressed file (`expression_matrix.tsv.gz`), while _test espression matrix_ is generated as a __CSV__ compressed file (`test_expression_matrix.csv.gz`), but `kerblam.toml` expects two CSVs...
https://github.com/TCP-Lab/transportome_profiler/blob/32f40b74b63527fc45b2e7e8f7e9dbf94ca237e6/kerblam.toml#L10
1. simply changing the TOML to
    ```toml
    [data.profiles.test]
    "expression_matrix.tsv.gz" = "test_expression_matrix.csv.gz"
    ```
    does not work because then `metasplit` crashes
    ```bash
    [WARNING] metasplit.core: I only read one header. This might mean you gave me the wrong delimiter. 
    ```
    I think that the culprit is `xsv fmt` trying to format an already CSV-formatted file (albeit with TSV extension).
